import { GET } from './route';

describe('Country endpoint tests', () => {
  it('it should return correct list of countries when called', async () => {
    const response = await GET();
    const data = await response.json();

    expect(data).toEqual(
      expect.objectContaining({
        countries: expect.arrayContaining([
          'Afghanistan',
          'Albania',
          'Algeria',
          'Angola',
          'Antarctica',
          'Argentina',
          'Armenia',
          'Australia',
          'Austria',
          'Azerbaijan',
          'Bahrain',
          'Bangladesh',
          'Belarus',
          'Belgium',
          'Benin',
          'Bhutan',
          'Bolivia',
          'Bosnia and Herzegovina',
          'Botswana',
          'Brazil',
          'Brunei Darussalam',
          'Bulgaria',
          'Burkina Faso',
          'Burundi',
          'Cambodia',
          'Cameroon',
          'Canada',
          'Cape Verde',
          'Central African Republic',
          'Chile',
          'China',
          'Colombia',
          'Congo',
          'Costa Rica',
          'Cote DIvoire',
          'Croatia',
          'Cuba',
          'Cyprus',
          'Czech Republic',
          'Democratic Republic of the Congo',
          'Denmark',
          'Djibouti',
          'Dominican Republic',
          'Ecuador',
          'Egypt',
          'El Salvador',
          'Equatorial Guinea',
          'Eritrea',
          'Estonia',
          'Ethiopia',
          'Fiji',
          'Finland',
          'France',
          'French Guiana',
          'Gabon',
          'Gambia',
          'Georgia',
          'Germany',
          'Ghana',
          'Greece',
          'Guatemala',
          'Guinea',
          'Guinea-Bissau',
          'Guyana',
          'Honduras',
          'Hungary',
          'Iceland',
          'India',
          'Indonesia',
          'Iran',
          'Iraq',
          'Ireland',
          'Israel',
          'Italy',
          'Jamaica',
          'Japan',
          'Jordan',
          'Kazakhstan',
          'Kenya',
          'Kosovo',
          'Kuwait',
          'Kyrgyzstan',
          'Laos',
          'Latvia',
          'Lebanon',
          'Lesotho',
          'Liberia',
          'Libya',
          'Lithuania',
          'Luxembourg',
          'Macedonia',
          'Madagascar',
          'Malawi',
          'Malaysia',
          'Mali',
          'Mauritania',
          'Mauritius',
          'Mexico',
          'Moldova',
          'Mongolia',
          'Montenegro',
          'Morocco',
          'Mozambique',
          'Myanmar',
          'Namibia',
          'Nepal',
          'Netherlands',
          'New Zealand',
          'Nicaragua',
          'Niger',
          'Nigeria',
          'North Korea',
          'Norway',
          'Oman',
          'Pakistan',
          'Palestine',
          'Panama',
          'Papua New Guinea',
          'Paraguay',
          'Peru',
          'Philippines',
          'Poland',
          'Portugal',
          'Qatar',
          'Romania',
          'Russia',
          'Rwanda',
          'Saint Lucia',
          'Saudi Arabia',
          'Senegal',
          'Serbia',
          'Sierra Leone',
          'Singapore',
          'Slovakia',
          'Slovenia',
          'South Africa',
          'South Korea',
          'Spain',
          'Sri Lanka',
          'Sudan',
          'Suriname',
          'Swaziland',
          'Sweden',
          'Switzerland',
          'Syrian Arab Republic',
          'Taiwan',
          'Tajikistan',
          'Tanzania',
          'Thailand',
          'Togo',
          'Trinidad and Tobago',
          'Tunisia',
          'Turkey',
          'Turkmenistan',
          'Uganda',
          'Ukraine',
          'United Arab Emirates',
          'United Kingdom',
          'United States of America',
          'Uruguay',
          'Uzbekistan',
          'Venezuela',
          'Vietnam',
          'Western Sahara',
          'Yemen',
          'Zambia',
          'Zimbabwe',
        ]),
      })
    );
  });
});
